package com.sqlgen.km.mb2dsl.generator;

import java.util.List;
import java.util.Map;

/**
 * Generates the sqlg.yaml configuration file.
 */
public class SqlgYamlWriter {

    /**
     * Generate sqlg.yaml content.
     *
     * @param javaPackage    the Java base package (e.g., "com.example")
     * @param mapperPackage  the mapper package (e.g., "com.example.mapper")
     * @param modelPackage   the entity/model package (e.g., "com.example.entity")
     * @param sqlFiles       list of .sql file names
     */
    public static String render(String javaPackage, String mapperPackage,
                                 String modelPackage, List<String> sqlFiles) {
        StringBuilder sb = new StringBuilder();
        sb.append("# sqlg.yaml — generated by mb2dsl\n");
        sb.append("# Review and adjust as needed.\n\n");
        sb.append("engines: [pg]\n\n");
        sb.append("java:\n");
        sb.append("  packages:\n");
        sb.append("    - modelPackage: \"").append(modelPackage != null ? modelPackage : "com.example.entity").append("\"\n");
        sb.append("      mapperPackage: \"").append(mapperPackage != null ? mapperPackage : "com.example.mapper").append("\"\n");
        sb.append("      out: \"src/main/java\"\n");
        sb.append("      files:\n");
        for (String sqlFile : sqlFiles) {
            sb.append("        - \"").append(sqlFile).append("\"\n");
        }
        return sb.toString();
    }
}
